# Generated by Django 4.2.6 on 2023-11-17 16:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_blogpost_publication_date'), ('blog', '0003_category_blogpost_category'), ('blog', '0004_alter_blogpost_category'), ('blog', '0005_alter_blogpost_category'), ('blog', '0006_alter_blogpost_content'), ('blog', '0007_blogpost_snippet'), ('blog', '0008_alter_blogpost_snippet'), ('blog', '0009_blogpost_header_image'), ('blog', '0010_profile'), ('blog', '0011_profile_profile_pic_profile_socialmedia_url'), ('blog', '0012_treatmentlog_profile_treatment_logs'), ('blog', '0013_remove_profile_treatment_logs')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication_date', models.DateField(auto_now_add=True, default=django.utils.timezone.now)),
                ('category', models.CharField(default='news', max_length=200)),
                ('snippet', models.CharField(max_length=200)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/images/')),
                ('socialmedia_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
