# Generated by Django 4.2.6 on 2023-11-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_treatmentlog_profile_treatment_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='treatment_logs',
        ),
    ]
